version: '2.2'
services:
  nginx:
    container_name: backend-nginx
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.nginx
      args:
        PHP_FPM_SERVER: php
        PHP_FPM_PORT: 9000
    ports:
      - ${DOCKER_NGINX_EXTERNAL_PORT-8080}:80
    depends_on:
      - php
    links:
      - php

  php:
    container_name: backend-php
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
      args:
        XDEBUG: "true"
    volumes:
      - /var/www/vendor
      - .:/var/www/
      - ./deployment/docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      APP_ENV: local
      PHP_IDE_CONFIG: serverName=ide-debugger-server
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal} remote_port=9001
    links:
      - mysql
      - redis

  redis:
    container_name: redis
    image: redis:5.0.6
    ports:
      - ${DOCKER_REDIS_EXTERNAL_PORT-6379}:6379

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
      - ./deployment/docker/mysql-database-test.sql:/docker-entrypoint-initdb.d/mysql-database-test.sql
    environment:
      MYSQL_DATABASE: docai
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - ${DOCKER_MYSQL_EXTERNAL_PORT-3306}:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - ${DOCKER_PMA_EXTERNAL_PORT-8088}:80

volumes:
  mysqldata:
    driver: local
